version: '3'

services:
  database:
    image: postgres:16.0-alpine3.18
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db-volume:/var/lib/postgresql/data
      
  api:
    image: rodrigorvsn/ac2:latest
    environment:
      SPRING_PROFILES_ACTIVE: cd
      DB_HOST: database
    ports:
      - "9090:9090"
    depends_on:
      - database

volumes:
  db-volume:
